apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: psychotherapie-seliger-adm
      auth:
        secretRef:
          name: gcp-secret-manager-credentials
          namespace: eso
          key: credentials.json
