apps:
  - name: argocd
    namespace: argocd
  - name: ingress-nginx
    namespace: ingress-nginx
  - name: cert-manager
    namespace: cert-manager
  - name: cert-manager-config
    namespace: cert-manager
    syncWave: "1"
