apps:
  - name: argocd
    namespace: argocd
  - name: ingress-nginx
    namespace: ingress-nginx
  - name: cert-manager
    namespace: cert-manager
  - name: cert-manager-config
    syncWave: "1"
  - name: eso
    namespace: eso
  - name: eso-config
    syncWave: "1"
    ignoreDifferences:
      - group: external-secrets.io
        kind: ClusterSecretStore
        jsonPointers:
          - /spec/provider/gcpsm/auth/secretRef
