argo-cd:
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.peter-laudel.de
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls: true
